[production]
dnr.Numbers_Framework.name = "Numbers Framework"
dnr.Numbers_Framework.ready = true
dnr.Numbers_Framework.version = "1.0.1"

dnr.Numbers_Framework.content_settings.numbering.strip_leading_zeros = true
dnr.Numbers_Framework.content_settings.numbering.require_ordering = true

; NF Introduction
dnr.Numbers_Framework.content.001.title = "Introduction"
dnr.Numbers_Framework.content.001.paragraph.001 = "p001.html"

dnr.Numbers_Framework.content.001_001.title = "Architecture Overview"
dnr.Numbers_Framework.content.001_001.parent = "001"
dnr.Numbers_Framework.content.001_001.paragraph.001 = "p001.html"

dnr.Numbers_Framework.content.001_002.title = "Release Notes"
dnr.Numbers_Framework.content.001_002.parent = "001"

dnr.Numbers_Framework.content.001_003.title = "Upgrading Notes"
dnr.Numbers_Framework.content.001_003.parent = "001"

dnr.Numbers_Framework.content.001_004.title = "Contribution Guidelines"
dnr.Numbers_Framework.content.001_004.parent = "001"

; NF Modules
dnr.Numbers_Framework.content.002.title = "Numbers Framework Modules"
dnr.Numbers_Framework.content.002.paragraph.001 = "p001.html"

dnr.Numbers_Framework.content.002_001.title = "Main Application"
dnr.Numbers_Framework.content.002_001.parent = "002"
dnr.Numbers_Framework.content.002_001.paragraph.001 = "p001.html"

dnr.Numbers_Framework.content.002_002.title = "Framework Module"
dnr.Numbers_Framework.content.002_002.parent = "002"
dnr.Numbers_Framework.content.002_002.paragraph.001 = "p001.html"

dnr.Numbers_Framework.content.002_002_001.title = "Framework Overview"
dnr.Numbers_Framework.content.002_002_001.parent = "002_002"
dnr.Numbers_Framework.content.002_002_001.paragraph.001 = "p001.html"

dnr.Numbers_Framework.content.002_002.title = "Framework Module"
dnr.Numbers_Framework.content.002_002.parent = "002"
dnr.Numbers_Framework.content.002_002.paragraph.001 = "p001.html"