[production]
dnr.name = "Numbers Framework"
dnr.ready = true
dnr.version = "1.0.0"

dnr.content_settings.numbering.strip_leading_zeros = true
dnr.content_settings.numbering.require_ordering = true

; NF Introduction
dnr.content.001.title = "Introduction"
dnr.content.001.folder = "/001_Introduction"
dnr.content.001.paragraph.001 = "p001_introduction.html"

dnr.content.001_001.title = "Architecture Overview"
dnr.content.001_001.folder = "/001_Introduction/001_001_Architecture_Overview"
dnr.content.001_001.parent = "001"
dnr.content.001_001.paragraph.001 = "p001_architecture_overview.html"

dnr.content.001_002.title = "Release Notes"
dnr.content.001_002.parent = "001"

dnr.content.001_003.title = "Upgrading Notes"
dnr.content.001_003.parent = "001"

dnr.content.001_004.title = "Contribution Guidelines"
dnr.content.001_004.parent = "001"

; NF Modules
dnr.content.002.title = "Modules"
dnr.content.002.folder = "/002_Modules"
dnr.content.002.paragraph.001 = "p001_numbers_framework_modules.html"

dnr.content.002_001.title = "Main Application"
dnr.content.002_001.parent = "002"
dnr.content.002_001.folder = "/002_Modules/002_001_Main_Application"
dnr.content.002_001.paragraph.001 = "p001_main_application.html"

dnr.content.002_002.title = "Framework Module"
dnr.content.002_002.parent = "002"
dnr.content.002_002.folder = "/002_Modules/002_002_Framework_Module"
dnr.content.002_002.paragraph.001 = "p001_framework_module.html"

dnr.content.002_002_001.title = "Framework Overview"
dnr.content.002_002_001.parent = "002_002"
dnr.content.002_002_001.folder = "/002_Modules/002_002_Framework_Module/002_002_001_Framework_Overview"
dnr.content.002_002_001.paragraph.001 = "p001_framework_overview.html"

dnr.content.002_002_002.title = "Framework Functionalities"
dnr.content.002_002_002.parent = "002_002"
dnr.content.002_002_002.folder = "/002_Modules/002_002_Framework_Module/002_002_002_Framework_Functionalities"
dnr.content.002_002_002.paragraph.001 = "p001_framework_functionalities.html"
dnr.content.002_002_002.paragraph.002 = "p002_application_folders.html"
dnr.content.002_002_002.paragraph.003 = "p003_vendor_repositories.html"
dnr.content.002_002_002.paragraph.004 = "p004_private_folders.html"
dnr.content.002_002_002.paragraph.005 = "p005_public_html_folder.html"
dnr.content.002_002_002.paragraph.006 = "p006_public_sites.html"

dnr.content.002_002_003.title = "ORM Classes"
dnr.content.002_002_003.parent = "002_002"
dnr.content.002_002_003.folder = "/002_Modules/002_002_Framework_Module/002_002_003_ORM_Classes"
dnr.content.002_002_003.paragraph.001 = "p001_orm_classes.html"
dnr.content.002_002_003.paragraph.002 = "p002_orm_tables.html"
dnr.content.002_002_003.paragraph.003 = "p003_orm_checks.html"

dnr.content.002_003.title = "Backend Module"
dnr.content.002_003.parent = "002"
dnr.content.002_003.folder = "/002_Modules/002_003_Backend_Module"
dnr.content.002_003.paragraph.001 = "p001_backend_module.html"

dnr.content.002_004.title = "Frontend Module"
dnr.content.002_004.parent = "002"
dnr.content.002_004.folder = "/002_Modules/002_004_Frontend_Module"
dnr.content.002_004.paragraph.001 = "p001_frontend_module.html"

